import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: '400',
});

export const metadata: Metadata = {
  title: "My Todo App",
  description: "Generated by create todolist app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-white`}>
        {children}
      </body>
    </html>
  );
}
